POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Elon Musk",
    "number": "123-456-7890"
}

### 
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "123-456-7890"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "123-456-7890"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Mary Poppendieck"
}




  